project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('prouducts/', include('prouducts.urls',namespace='products')),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prouducts/urls.py
from django.urls import path
from .views import items_list,itemsDetail,brand_list,brand_detail,category_list,postList
app_name='prouducts'
urlpatterns = [
    path('test',postList),
    path('',items_list.as_view(),name='items_list'),
    path('<int:pk>',itemsDetail.as_view(),name='items_detail'),
    path('brands/',brand_list.as_view(),name='brand_list'),
    path('brands/<int:pk>',brand_detail.as_view(),name='brand_detail'),
    path('cateogry/',category_list.as_view(),name='category_list'),
 ]

prouducts/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
# Create your models here.
#one for user and one for database
prouduct_flag=[
    ('new','new'),
    ('sold','sold'),
    ('features','features'),
]
class items(models.Model):
    name=models.CharField(verbose_name=_('Name'), max_length=50)
    flag=models.CharField(_('Flag'),choices=prouduct_flag,max_length=10)
    price=models.FloatField(_('Price'))
    sku=models.IntegerField(_('Sku'))
    subtitle=models.CharField(verbose_name=_('subtitle'), max_length=500)
    tag=TaggableManager()
    vedio=models.URLField(_('vedio'),null=True,blank=True)
    cateogry=models.ForeignKey('cateogry',verbose_name=_('cateogry'),related_name='cateogry_item',on_delete=models.SET_NULL,null=True,blank=True)
    brand=models.ForeignKey('brand',verbose_name=_('brand'),related_name='brand_item',on_delete=models.SET_NULL,null=True,blank=True)
    itemimage=models.ImageField(_('Image'),upload_to='items')
    def __str__(self) -> str:
        return self.name

class cateogry(models.Model):
    name=models.CharField(verbose_name=_('Name'), max_length=50)
    image=models.ImageField(_('Image'),upload_to='cateogry')
    def __str__(self) -> str:
        return str(self.name)

class brand(models.Model):
    name=models.CharField(verbose_name=_('Name'), max_length=50)
    image=models.ImageField(_('Image'),upload_to='brand')
    def __str__(self) -> str:
        return str(self.name)

class review(models.Model):
    user=models.ForeignKey(User,verbose_name=_('user'), related_name='product_review',on_delete=models.SET_NULL,null=True,blank=True)
    product=models.ImageField(_('Image'),upload_to='reviwe')
    rate=models.IntegerField(_('rate'))
    review_content=models.CharField(_('reveiwcontent'),max_length=500)
    timeofreview=models.DateTimeField(default=timezone.now)
    def __str__(self) -> str:
        return self.product

class itemimages(models.Model):
    items=models.ForeignKey('items',verbose_name=_('itemimage'),related_name='image_item',on_delete=models.SET_NULL,null=True,blank=True)
    image=models.ImageField(_('Image'),upload_to='itemimages')
    def __str__(self) -> str:
        return str(self.items)
        

prouducts/views.py
from itertools import product
from multiprocessing import get_context
from django.shortcuts import render
from django.views.generic import ListView ,DetailView
from .models import items,itemimages,cateogry,brand
from django.db.models import Count,Q,F


def postList(requset):
    #objects=items.objects.all()
    #use filter
    #gt=greater than
    #lt=lettle than
    #lte=lettle than or equal the same in gte
    #objects=items.objects.filter(price__gt=30)
    #objects=items.objects.filter(price__range=[30,100])
    #objects=items.objects.filter(cateogry__id__gt=10)
    #objects=items.objects.filter(cateogry__id__lt=10)
    #objects=items.objects.filter(name__contains='k')
    #objects=items.objects.filter(name__startswith='k')
    #objects=items.objects.filter(name__endswith='r')
    #objects=items.objects.filter(name__isnull=True)
    #or
    #objects=items.objects.filter(Q(price__gt=30)|Q(name__startswith='k'))
    #not and
    #objects=items.objects.filter(Q(price__gt=30)&~Q(name__startswith='k'))
    #and
    #objects=items.objects.filter(Q(price__gt=30)&Q(name__startswith='k'))
    #for compaire two columns we will use refrance felied(f)
    #objects=items.objects.filter(price=F('quantity'))
    #for compare two column relations
    #objects=items.objects.filter(price=F('category__id'))
    return render(requset,'prouducts/test_list.html',{'items':objects})
# Create your views here.
class items_list(ListView):
    model=items
    #paginate is function in cbv
    paginate_by=20
# there are method in detail veiw contain the context two get details of the model but i want show the image from the second
#model in second class "proudct image " to show them by other context so i will make override
class itemsDetail(DetailView):
    model=items
    #override to immplemnt the fun in the two classes
    def get_context_data(self, **kwargs):
        #super responsable of implemint the context in the first class then implement the other context
        # detail , edit ,delete that deploy on one thing there are function speacial for them ----> get_object
        context=super().get_context_data(**kwargs)
        #item isthe product with the the id in url
        myitem=self.get_object()
        #the second fun will immplement by second contesxt from other class
        context["image"]=itemimages.objects.filter(items=myitem)
        context["related"]=items.objects.filter(cateogry=myitem.cateogry)#[1:10]#toslice
        return context

class brand_list(ListView):
    model=brand
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["brands"]=brand.objects.all().annotate(items_count=Count('brand_item'))
        return context


class brand_detail(DetailView):
    model=brand
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        brand=self.get_object()
        context["brand_product"]=items.objects.filter(brand=brand)
        return context

class category_list(ListView):
    model=cateogry
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["cateogry"]=cateogry.objects.all().annotate(items_count=Count('cateogry_item'))
        return context

prouducts/templates/prouducts/brand_detail.html
{% extends "base.html" %}
{% load static %}
{% block mystatic %}
<link rel="stylesheet" href="{% static 'css/brand-single.css' %}">
{% endblock mystatic %}
{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand.name}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>(45 items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->
        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    {% for product in brand_product %}
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{product.flag}}</label>
                                    </div>
                                    <button class="product-wish wish">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                    <a class="product-image" href="{% url 'products:items_detail' product.id %}">
                                        <img src="{{product.itemimage.url}}" alt="product">
                                    </a>
                                    <div class="product-widget">
                                        <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                        <a title="Product Video" href="{{product.vedio_url}}" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                        <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="icofont-star"></i>
                                        <a href="product-video.html">{{product.id}}</a>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:items_detail' product.id %}">{{product.name}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        <del>$34</del>
                                        <span>{{product.price}}<small>/piece</small></span>
                                    </h6>
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->

{% endblock body %}

prouducts/templates/prouducts/brand_list.html
{% extends "base.html" %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for brand in brands %}
                        <div class="col all vegetables">
                            <div class="brand-wrap">
                                <div class="brand-media">
                                    <img src="{{brand.image.url}}" alt="brand">
                                    <div class="brand-overlay">
                                        <a href="{% url 'products:brand_detail' brand.id %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="brand-meta">
                                    <h4>{{brand.name}}</h4>
                                    <p>{{brand.items_count}}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!--  لو بترو هيظهر غير كدا لاis_paginatedلو عملت دالة الباجينيت بترجع متغير قيمتة بترو او فولس اسمه -->
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    <!--previous
                                    there is var named page_object returned from the var of paginated in veiw
                                    in cbv we will ask irt if there is pages befor you or not-->
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.has_previous_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item" disabled><i class="fas fa-long-arrow-alt-left"></i></i>
                                    {% endif %}
                                    <!--paginator returned from view from cbv for active page-->
                                    {% for page in paginator.page_range %}
                                        {% if page_obj.number == page %}
                                            <li class="page-item"><a class="page-link active" href="#">{{page}}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.has_next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item" disabled></i>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->
        {% endblock body %}
        <!--الباجينيشن متقسم ل 3 اجزاء ال بريفيس والنيكست والاكتيف واللي ف النص -->

prouducts/templates/prouducts/cateogry_list.html
{% extends "base.html" %}
{% block body %}
        <!--=====================================
                    CATEGORY PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
                    {% for item in cateogry %}
                        <div class="col">
                            <div class="category-wrap">
                                <div class="category-media">
                                    <img src="{{item.image.url}}" alt="category">
                                    <div class="category-overlay">
                                        <a href="{% url 'prouducts:items_list' %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="category-meta">
                                    <h4>{{item.name}}</h4>
                                    <p>[{{item.items_count}} items]</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <!--previous
                                there is var named page_object returned from the var of paginated in veiw
                                in cbv we will ask irt if there is pages befor you or not-->
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.has_previous_page_number}}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item" disabled><i class="fas fa-long-arrow-alt-left"></i></i>
                                {% endif %}
                                <!--paginator returned from view from cbv for active page-->
                                {% for page in paginator.page_range %}
                                    {% if page_obj.number == page %}
                                        <li class="page-item"><a class="page-link active" href="#">{{page}}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.has_next_page_number}}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item" disabled></i>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        

        <!--=====================================
                    NEWSLETTER PART START
        =======================================-->
        <section class="news-part" style="background: url(images/newsletter.jpg) no-repeat center;">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-5 col-lg-6 col-xl-7">
                        <div class="news-text">
                            <h2>Get 20% Discount for Subscriber</h2>
                            <p>Lorem ipsum dolor consectetur adipisicing accusantium</p>
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <form class="news-form">
                            <input type="text" placeholder="Enter Your Email Address">
                            <button><span><i class="icofont-ui-email"></i>Subscribe</span></button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    CATEGORY PART END
        =======================================-->

{% endblock body %}

prouducts/templates/prouducts/test_list.html
<!--debuger tool dedn't appear without html structure-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for item in items %}
            <li>{{item}}--{{item.price}}--{{item.cateogry}}</li>
        {% endfor %}
        </ul>  
</body>
</html>